---
title: "Book outline"
format: html
editor: visual
---

# Project introduction

## Acknowledgments (subsection)

# City food policies to meet sustainable development goals

## International public food procurement

## U.S. public food procurment

## New York City public food procurment

### New York City agency specific procurment information

this is where the NYC data overview, this is what NYC has on their dashboard, overall trends in purchasing

# Research question

## How did we choose our commodities

### New York City data

This is where we put all of the data collected by Rebecca New York state ag data (Census of Ag, etc.) \## Selected food policy actions Aiden put this together and Dana/Michael have a nice visual to add \### New York City legal framework (Aiden) \### NYC baseline purchasing by food policy action This is what Rebecca is currently working on

# New York State supply chains

## Beef

### Secondary data

### Stakeholder engagment and validation

This is where all the focus group Survey instrument will be referenced and in an appendix \#### Causal loop diagram This will either be a link or an image, whatever is best \#### Focus group

## Dry beans

## Greens

# Modelling approach

### Food policy actions

# Dry Beans

## Supply chain overview

## Agricultural production

### Farm inputs and production costs

## Processing

## Distribution

## Markets

## Estimated margins

## Consumption

## Institutional purchasing in New York state

# Beef

# Lettuce
