---
format: html
editor: visual
bibliography: ../references.bib
---

# Agent behavior and decision making

To analyze interviews and focus group data, we used the following process:

1.  Open Coding System: Transcripts were coded inductively, guided by the research questions (@glaser_open_coding_2016, @saldana_coding_manual_2025). The research team developed thematic memos for each producer group (beans, beef/dairy, leafy greens) through collaborative "theming" (@saldana_coding_manual_2025), returning to original transcripts throughout to preserve participants' language. This produced four thematic areas: (1) personal values, (2) relationships and reliability, (3) market conditions, and (4) logistics and infrastructure.
2.  Secondary Coding: Transcripts were recoded using MAXQDA to identify key internal and external drivers within each theme. A structured codebook, which defined core themes as well as internal and external influences, was developed based on thematic memos generated during the analysis.
3.  Mapping to COM-B Framework: Following prior applications of inductive coding to adapted COM-B frameworks (@Ambrose-Oji_2022, @Evans_common_sense_2025, @Farrell_vet_2023, @Mastenbroek_seed_demand_2025), our study first inductively identified themes and internal/external factors, then deductively mapping those findings onto the adapted framework's three domains to explore how potential NYC procurement policies might influence current behaviors.

## How base agents respond to requests with offers

## Scoring incoming requests for product in the model
