---
format: html
editor: visual
---

[Final data: Total demand for New York State differentiated dry beans.](https://github.com/FoodSystemsModeling/CityFoodPolicy/blob/main/drybeans/data_final/differentiated_total_demand.xls)

To determine to total market for NYS differentiated beans, four dry bean growers with food grade cleaning capacity who sell directly to buyers were contacted (interviews, emails, phone calls). Sales data was provided by the producer. (Numbers were confirmed to make sure they are not double counted in the totals).

```{r}
#| include: false
# When included in the book, working dir is drybeans/ not data_inputs_code/
# Detect context: if data_inputs_code/ exists as a subdirectory, we're in the parent (book render)
if (!dir.exists("../data_final") && dir.exists("data_inputs_code")) {
  knitr::opts_knit$set(root.dir = normalizePath("data_inputs_code"))
}
```

```{r}
#wb <- createWorkbook()

# Create data frame with information
diff <- tibble(
  type = "differentiated", 
  commodity = "drybeans", 
  variable = "total_demand_kg", 
  value = 1248762/2.205
)

# Write info txt
info <- c(
  'sheet_name = "differentiated_market_size"', 
  'description = "Total size of the differentiated market (i.e., NYS source identified) dry beans"', 
  'source = "interviews"', 
  'notes = "Data are reported in total killograms of dry beans"'
)

# Save
write_csv(diff, "../data_final/differentiated_total_demand.csv")
writeLines(info, "../data_final/differentiated_total_demand.txt")

```
